"""Render ENV_VARS.md from the configuration manifest.

This document had drifted into describing variables that do not exist, listing a computed
property as a required input, and carrying a placeholder cell. Making it generated is the
fix; every fact below comes from the manifest, so it cannot describe anything the extractors
did not find.
"""

from __future__ import annotations

from typing import Any

from repo_governance.config import Context
from repo_governance.extractors.configuration import template_sections

HEADER = """<!-- GENERATED by `make governance-sync` from governance/manifests/generated/configuration.json.
     Do not edit by hand: your changes will be overwritten and the check will fail first. -->

# Environment variables

Every variable governance can find across the backend settings, both environment templates,
and the Compose files. Names and classifications only — no value that could be a credential
appears here or in any other governance artifact.

| Class | Meaning |
| --- | --- |
| `runtime` | Read from the environment when the process starts. |
| `build-arg` | Baked into an image at build time. Changing it needs a rebuild; a restart will not pick it up. |
| `computed` | Derived by the settings object from other variables. **Not settable** — setting it has no effect. |
| `secret` | Credential. Never given a default here, whatever the source says. |
| `deprecated-alias` | Kept for compatibility; use the variable it aliases. |
| `compose-only` | Consumed by Compose, not by the application settings. |
| `unknown-consumer` | Present in a template with no reader found. Setting it does nothing. |
"""


def _escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _cell(value: str | None) -> str:
    return _escape(value) if value else "—"


def _required(value: Any) -> str:
    if value is True:
        return "yes"
    if value is False:
        return "no"
    return _escape(str(value))


def _row(variable: dict[str, Any]) -> str:
    name = variable["name"]
    classes = ", ".join(f"`{item}`" for item in variable.get("classification", []))
    default = "—"
    if "secret" in variable.get("classification", []):
        default = "*(secret — never recorded)*"
    elif variable.get("default_class") == "generated":
        default = "*(derived)*"
    elif variable.get("default") is not None:
        default = f"`{_escape(str(variable['default']))}`"

    description = variable.get("description") or ""
    if variable.get("alias_of"):
        alias_note = f"Alias of `{variable['alias_of']}`."
        milestone = variable.get("removal_milestone")
        if milestone:
            alias_note += f" Removal: {milestone}."
        description = f"{alias_note} {description}".strip()

    return f"| `{name}` | {_required(variable.get('required'))} | {default} | {classes} | {_cell(description)} |"


def render_env_vars(ctx: Context, configuration: dict[str, Any]) -> str:
    """Render the document, ordering sections the way the templates themselves read."""
    by_name = {variable["name"]: variable for variable in configuration.get("variables", [])}
    rendered: set[str] = set()
    parts: list[str] = [HEADER]

    for label, template in (
        ("Backend", ctx.repo_root / "backend" / ".env.example"),
        ("Frontend", ctx.repo_root / "frontend" / ".env.example"),
    ):
        sections = template_sections(template)
        if not sections:
            continue
        parts.append(f"\n## {label}\n")
        for section, names in sections:
            rows = [_row(by_name[name]) for name in names if name in by_name and name not in rendered]
            rendered.update(name for name in names if name in by_name)
            if not rows:
                continue
            parts.append(f"\n### {section}\n")
            parts.append("\n| Variable | Required | Default | Class | Description |")
            parts.append("\n| --- | --- | --- | --- | --- |\n")
            parts.append("\n".join(rows))
            parts.append("\n")

    remaining = [by_name[name] for name in sorted(by_name) if name not in rendered]
    if remaining:
        parts.append("\n## Declared elsewhere\n")
        parts.append(
            "\nVariables that appear in the settings module, the Compose files, or the frontend "
            "source, but in neither environment template. A template omission is worth noticing: "
            "it is how a required variable becomes undiscoverable.\n"
        )
        parts.append("\n| Variable | Required | Default | Class | Description |")
        parts.append("\n| --- | --- | --- | --- | --- |\n")
        parts.append("\n".join(_row(variable) for variable in remaining))
        parts.append("\n")

    findings = configuration.get("findings", [])
    open_findings = [finding for finding in findings if finding.get("status") == "open"]
    if open_findings:
        parts.append("\n## Open findings on the configuration surface\n\n")
        for finding in open_findings:
            parts.append(f"- **{finding['kind']}** — {_escape(finding['detail'])}\n")

    return "".join(parts)
