"""Render Summary.md from the effective manifest and the change history.

Deliberately bounded. This is the document an agent reads to orient itself, so it holds
current state, what is unresolved, and recent material history — not the permanent record.
Older change records stay queryable under `history/changes/` rather than accumulating here
until nobody reads any of it.
"""

from __future__ import annotations

from typing import Any

from repo_governance.config import Context, iter_files
from repo_governance.io_atomic import read_json

#: How many recent changes to show. The blueprint's range is 15 to 25; more than that and
#: the document stops being scannable, which defeats its purpose.
RECENT_CHANGES = 20


def _load_records(ctx: Context) -> list[dict[str, Any]]:
    records = []
    for path in iter_files(ctx.paths.changes, suffixes=(".json",)):
        try:
            records.append(read_json(path))
        except ValueError:
            continue
    return sorted(records, key=lambda item: (item.get("date", ""), item.get("id", "")), reverse=True)


#: Ordering within a single date. Change records carry a date but no clock time, so several
#: records from one day have no chronology to read — sorting them by ID is alphabetical, not
#: temporal. Resolving by status instead: a closure is necessarily a later statement than the
#: registration that made it necessary, because you cannot close a finding that was never
#: opened. Re-opening therefore requires a later date or a distinct finding ID, which is a
#: reasonable thing to ask of a re-opening.
_STATUS_PRECEDENCE = {"open": 0, "accepted": 1, "resolved": 2}


def _open_findings(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Latest disposition wins: a finding resolved by a later change is not still open."""
    latest: dict[str, dict[str, Any]] = {}
    for record in reversed(records):  # oldest first, so later records overwrite
        for finding in record.get("findings", []):
            existing = latest.get(finding["id"])
            if existing is not None and _STATUS_PRECEDENCE.get(
                existing.get("status", "open"), 0
            ) > _STATUS_PRECEDENCE.get(finding.get("status", "open"), 0):
                continue
            latest[finding["id"]] = finding
    order = {"high": 0, "medium": 1, "low": 2}
    return sorted(
        (finding for finding in latest.values() if finding.get("status") == "open"),
        key=lambda item: (order.get(item.get("severity", "low"), 3), item["id"]),
    )


def render_summary(
    ctx: Context,
    *,
    effective: dict[str, Any],
    decision_index: dict[str, Any],
    interfaces: dict[str, Any],
) -> str:
    """Render the summary from values already computed in this render pass.

    The generated inputs are passed in rather than read back from disk. Reading them would
    make the first sync of a clean checkout render a summary of files that do not exist yet,
    and the next sync would fill them in — non-idempotent in exactly the place a fresh CI
    checkout notices. The same trap the catalog falls into if its own entry is derived from
    the filesystem.
    """
    records = _load_records(ctx)
    parts: list[str] = [
        "<!-- GENERATED by `make governance-sync`. Do not edit by hand. -->\n",
        "\n# Governance summary\n",
        "\nCurrent state, what is unresolved, and recent material history. This is not the "
        "permanent record — older changes stay queryable under `governance/history/changes/`.\n",
    ]

    if effective:
        components = effective.get("components", [])
        by_kind: dict[str, list[str]] = {}
        for component in components:
            by_kind.setdefault(component["kind"], []).append(component["id"])

        parts.append(f"\n## Components ({len(components)})\n\n")
        for kind in sorted(by_kind):
            parts.append(f"- **{kind}** — {', '.join(sorted(by_kind[kind]))}\n")

        conflicts = effective.get("conflicts", [])
        if conflicts:
            parts.append("\n### Unresolved merge conflicts\n\n")
            for conflict in conflicts:
                parts.append(f"- `{conflict['component']}` / {conflict['field']} — {conflict['detail']}\n")

    findings = _open_findings(records)
    parts.append(f"\n## Open findings ({len(findings)})\n\n")
    if not findings:
        parts.append("None.\n")
    for finding in findings:
        parts.append(
            f"- **{finding['id']}** ({finding['severity']}) — {finding['detail']}\n"
            f"  - Disposition: {finding['disposition']}\n"
        )

    exceptions_path = ctx.paths.curated_manifests / "exceptions.json"
    if exceptions_path.is_file():
        active = [
            entry for entry in read_json(exceptions_path).get("exceptions", []) if entry.get("status") == "active"
        ]
        parts.append(f"\n## Accepted exceptions ({len(active)})\n\n")
        for entry in sorted(active, key=lambda item: item["id"]):
            parts.append(f"- **{entry['id']}** — {entry['statement']}\n")
            parts.append(f"  - Revisit when: {entry.get('review_trigger', 'not stated')}\n")

    contracts = _active_contracts(ctx, interfaces)
    if contracts:
        parts.append("\n## Active contracts\n\n")
        for name, detail in contracts:
            parts.append(f"- **{name}** — {detail}\n")

    parts.append(f"\n## Recent changes (latest {min(RECENT_CHANGES, len(records))} of {len(records)})\n\n")
    for record in records[:RECENT_CHANGES]:
        components = ", ".join(record.get("affected_components", [])) or "none recorded"
        parts.append(f"- **{record['date']}** — {record['summary']}\n")
        parts.append(f"  - Components: {components}\n")
        parts.append(f"  - Record: `governance/history/changes/{record['id']}.json`\n")

    decisions = decision_index.get("decisions", [])
    if decisions:
        parts.append(f"\n## Decisions ({len(decisions)})\n\n")
        for decision in decisions:
            parts.append(f"- **{decision['id']}** — {decision['title']} ({decision['status']})\n")

    return "".join(parts)


def _active_contracts(ctx: Context, interfaces: dict[str, Any]) -> list[tuple[str, str]]:
    """The cross-file agreements that can break silently."""
    contracts: list[tuple[str, str]] = []

    data_stores = ctx.paths.generated_manifests / "data-stores.json"
    if data_stores.is_file():
        document = read_json(data_stores)
        dimension = document.get("postgres", {}).get("dimension_contract")
        if dimension:
            contracts.append(
                (
                    "Embedding dimension",
                    f"{dimension['expected']} across {len(dimension['points'])} points that must agree; see ADR-002.",
                )
            )
        migrations = document.get("postgres", {}).get("migrations", {})
        if migrations.get("head_expected"):
            contracts.append(("Migration head", ", ".join(migrations["head_expected"])))
        redis = document.get("redis", {}).get("databases", [])
        if redis:
            allocations = "; ".join(f"{entry['db']} {entry['purpose']}" for entry in redis)
            contracts.append(("Redis logical databases", allocations))

    if interfaces:
        proxy_count = len(interfaces.get("proxy_routes", []))
        contracts.append(
            (
                "Proxy layer",
                f"{proxy_count} handlers front every REST call; the chat WebSocket at "
                f"{interfaces.get('websocket', {}).get('endpoint')} is the only documented exception.",
            )
        )

    return contracts
