"""The single writer for every generated governance file.

Determinism is a kernel requirement: two syncs with no source change must produce
byte-identical output, on Windows as well as CI. Every generated byte therefore goes
through this module, which guarantees:

* LF-only line endings (never CRLF), regardless of platform;
* UTF-8 without a BOM;
* JSON with sorted keys and a stable two-space indent, one trailing newline;
* forward-slash path normalization for anything path-shaped;
* atomic replacement via a temp file in the destination directory plus `os.replace`.

No generated file may carry a timestamp, a hostname, an absolute path, or any other
volatile value. If a fact is volatile, it belongs in runtime evidence under
`.cache/repo-governance/`, not in a committed manifest.
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path, PurePosixPath
from typing import Any

ENCODING = "utf-8"
GENERATED_MARKER = "GENERATED by `make governance-sync`"


def canonical_json(data: Any) -> str:
    """Render `data` as the canonical governance JSON form."""
    return json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def normalize_newlines(text: str) -> str:
    """Collapse CRLF and lone CR to LF."""
    return text.replace("\r\n", "\n").replace("\r", "\n")


def posix(path: str | Path) -> str:
    """Normalize a path to forward slashes.

    Used for every path that lands in a manifest, so a Windows checkout and a Linux CI
    runner emit identical bytes.
    """
    return PurePosixPath(str(path).replace("\\", "/")).as_posix()


def relative_posix(path: Path, root: Path) -> str:
    """Express `path` relative to `root` in forward-slash form."""
    return posix(path.resolve().relative_to(root.resolve()))


def render_bytes(text: str) -> bytes:
    """The exact bytes this module would write for `text`."""
    return normalize_newlines(text).encode(ENCODING)


def write_text_atomic(path: Path, text: str) -> bool:
    """Write `text` atomically. Returns True when the on-disk bytes changed.

    A no-op write is reported as False and does not touch the file, so an unchanged sync
    leaves mtimes alone and produces no git churn.
    """
    data = render_bytes(text)
    if path.exists() and path.read_bytes() == data:
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), prefix=".governance-tmp-", suffix=".part")
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_path, path)
    except BaseException:
        tmp_path.unlink(missing_ok=True)
        raise
    return True


def write_json_atomic(path: Path, data: Any) -> bool:
    """Write `data` as canonical governance JSON. Returns True when bytes changed."""
    return write_text_atomic(path, canonical_json(data))


def read_json(path: Path) -> Any:
    """Read JSON with explicit UTF-8 decoding, tolerating a BOM on hand-edited files."""
    raw = path.read_bytes()
    if raw.startswith(b"\xef\xbb\xbf"):
        raw = raw[3:]
    return json.loads(raw.decode(ENCODING))
